package OOPS.encapsulation;

//TODO: package is just like a folder for better structure
//

public class EncapsulationIntro {
    public static void main(String[] args) {
        Laptop l1 = new Laptop();
         // l1.price = 32; this will not work
        l1.setPrice(32);
        System.out.println(l1.getPrice());
        System.out.println(l1.ram);
    }




    public void doWork(){
        System.out.println("I am from package OOPS.encapsulation;");
    } // why public?
    // TODO: coz of public keyword we can access it from any where- from bascis.MainClass.java also


    //Access modifier
    // If we use private then it can only be accessed from within EncapsulationIntro
    // No access from outside
    private void doWorkPrivate(){
        System.out.println("Private access modifier");
    }

    //Protected - if we want properties to be accessible to only children then
    // we can mark them as protected - i.e.

}


// Methods and variable encapsulated within a capsule
class Laptop{
    int ram;
    private int price;


    public void setPrice(int price){
        // if(user == admin){
        this.price = price;
    }

    // Getters and setters generated by intellj
    public int getPrice() {
        return price;
    }

    public void setRam(int ram) {
        this.ram = ram;
    }
}

